---
all:
  children:

    surface:
      hosts:

        surface-pro-7-plus:
          ansible_host: surface-pro-7-plus
          ansible_user: shackadmin
          surface_model: "Microsoft Surface Pro 7+"
          surface_generation: "surface-pro-7-plus"
